version: '3.3'

networks:
  laravel: 

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - mysql
    networks:
      - laravel

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    env_file: ./app.env
    volumes:
      - ./src:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homebase
      MYSQL_USER: blackcat
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: secret123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
